[package]
name = "mithril-signer"
version = "0.2.89"
description = "A Mithril Signer"
authors = { workspace = true }
edition = { workspace = true }
documentation = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
anyhow = "1.0.75"
async-trait = "0.1.73"
clap = { version = "4.4.6", features = ["derive", "env"] }
config = "0.13.3"
hex = "0.4.3"
mithril-common = { path = "../mithril-common" }
openssl = { version = "0.10.57", features = ["vendored"], optional = true }
openssl-probe = { version = "0.1.5", optional = true }
rand_chacha = "0.3.1"
rand_core = "0.6.4"
reqwest = { version = "0.11.22", features = ["json", "stream"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
slog = { version = "2.7.0", features = [
    "max_level_trace",
    "release_max_level_debug",
] }
slog-async = "2.8.0"
slog-bunyan = "2.4.0"
slog-scope = "4.4.0"
sqlite = { version = "0.31.1", features = ["bundled"] }
thiserror = "1.0.49"
tokio = { version = "1.32.0", features = ["full"] }

[dev-dependencies]
httpmock = "0.6.8"
mithril-common = { path = "../mithril-common" }
mockall = "0.11.4"
slog-term = "2.9.0"

[features]
portable = [
    "mithril-common/portable",
] # portable feature avoids SIGILL crashes on CPUs not supporting Intel ADX instruction set when built on CPUs that support it
bundle_openssl = ["dep:openssl", "dep:openssl-probe"]
