[package]
name = "mithril-client-cli"
version = "0.5.2"
description = "A Mithril Client"
authors = { workspace = true }
edition = { workspace = true }
documentation = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[[bin]]
name = "mithril-client"
path = "src/main.rs"
required-features = ["build-binary"]

[lib]
name = "mithril_client"
crate-type = ["lib", "cdylib", "staticlib"]

[package.metadata.deb]
depends = "$auto"
section = "utility"
features = ["build-binary"]
extended-description = """Shows, downloads and verifies certified blockchain artifacts.

Run `mithril-client --help` to display the available options."""
assets = [["../target/release/mithril-client", "usr/bin/", "755"]]

[dependencies]
anyhow = "1.0.75"
async-recursion = "1.0.5"
async-trait = "0.1.73"
chrono = { version = "0.4.31", features = ["serde"] }
clap = { version = "4.4.6", features = ["derive", "env"], optional = true }
cli-table = { version = "0.4.7", optional = true }
config = { version = "0.13.3", optional = true }
directories = "5.0.1"
flate2 = "1.0.27"
flume = "0.11.0"
fs2 = "0.4.3"
futures = "0.3.28"
hex = "0.4.3"
human_bytes = { version = "0.4.3", features = ["fast"] }
indicatif = { version = "0.17.7", features = ["tokio"] }
mithril-common = { path = "../mithril-common" }
openssl = { version = "0.10.57", features = ["vendored"], optional = true }
openssl-probe = { version = "0.1.5", optional = true }
reqwest = { version = "0.11.22", features = ["json", "stream"] }
semver = "1.0.19"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
slog = { version = "2.7.0", features = [
    "max_level_trace",
    "release_max_level_debug",
] }
slog-async = "2.8.0"
slog-scope = "4.4.0"
slog-term = "2.9.0"
tar = "0.4.40"
thiserror = "1.0.49"
tokio = { version = "1.32.0", features = ["full"] }
zstd = "0.13.0"

[dev-dependencies]
httpmock = "0.6.8"
mithril-common = { path = "../mithril-common" }
mockall = "0.11.4"
warp = "0.3"

[features]
portable = ["mithril-common/portable"]
bundle_openssl = ["dep:openssl", "dep:openssl-probe"]
build-binary = ["clap", "config", "cli-table"]
