[package]
name = "mithril-client"
version = "0.5.4"
description = "Mithril Client library"
authors = { workspace = true }
edition = { workspace = true }
documentation = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
anyhow = "1.0.75"
async-recursion = "1.0.5"
async-trait = "0.1.73"
chrono = { version = "0.4.31", features = ["serde"] }
flate2 = "1.0.27"
flume = "0.11.0"
futures = "0.3.28"
mithril-common = { path = "../mithril-common" }
reqwest = { version = "0.11.22", features = ["json", "stream"] }
semver = "1.0.19"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
slog = "2.7.0"
tar = "0.4.40"
thiserror = "1.0.49"
tokio = { version = "1.32.0", features = ["sync"] }
uuid = { version = "1.5.0", features = ["v4"] }
zstd = "0.13.0"

[dev-dependencies]
httpmock = "0.6.8"
indicatif = { version = "0.17.7", features = ["tokio"] }
mithril-common = { path = "../mithril-common", features = ["test_http_server"] }
mockall = "0.11.4"
slog-async = "2.8.0"
slog-scope = "4.4.0"
slog-term = "2.9.0"
tokio = { version = "1.32.0", features = ["macros", "rt"] }
warp = "0.3"

[features]
portable = ["mithril-common/portable"]
